# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zscVbyGXNN-ghE15LZlfvMm2JI-cHxWN
"""





List_L1 = [2, 4, 6, 8, 10]
List_L2 =[1, 3, 5, 7, 9]
L3 = List_L1 + List_L2
print(L3)

# List_angle = [0,30,60,90,120,150,180,210,240,270,300,330,360]
list_angle=list(range(0, 360 , 30))
list_angle

list_angle = [0,30,60,90,120,150,180,210,240,270,300,330,360] ;
i1 = angle.index( '90' )
# print "i1 : ", angle.index( '0' )



angle = [0,30,60,90,120,150,180,210,240,270,300,330,360]
i1 = angle.index(90, [0, [360]])

angle = [0,30,60,90,120,150,180,210,240,270,300,330,360]
i2=angle.index(270)
print i2





"""int main()
{
    printf("Hello, World!");
   return 0;
}
"""